spring: 
  application: 
    name: eurekaServer
  security:
    basic:  
      enabled: true  
    user: 
      name: "eurekaUser"
      password: "eurekaPwd"
      #_originalPwd: "eurekaPwd"
      #password: "$2a$10$xFBzhHiQ0rB0B.QK8dkH5eSzZeVqxzqfRccSX/PbFOg9XWn48.X8S"
---
spring:
  profiles: eurekaServer1
eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8083/eureka/
---
spring:
  profiles: eurekaServer2
eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8082/eureka/